name: advec
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - gdal
  - rasterio
  - matplotlib
  - xarray
  - dask
  - netCDF
  - bottleneck
  - rioxarray
  - cfgrib
  - wradlib
  - joblib
  - boto3
  - pip:
    - geopy
